PlayBook

# ansible -m file -a 'path=/tmp/kddhamo.txt.txt state=present' all
# YAML - yet another markup lang
- name: create at new file and delete it.
  hosts: all
  tasks:
    - name: create username file in tmp directory
      file:
        path: '/tmp/kddhamo.txt'
        state: touch

# touch hello.yml
# gedit or vi hello.yml
# :wq
# ansible-playbook hello.yml