---
kind: ReplicationController
apiVersion: v1
metadata:
  name: myreplica 
spec:
  replicas: 3 # how many pods need to create
  selector: # which pod to watch/belong to rc
    myname: Surekha # much match the label
  
  template: # what will be inside pod that we defind on template
    metadata:
      name: testpod6 # name of pof
      labels: # label on pof
        myname: Surekha
    spec: # what will be inside pod / contaier inside pof
      containers:
        - name: c00
          image: ubuntu
          command:
            [
              "/bin/bash",
              "-c",
              "while true; do echo Hello-wolld ; sleep 5 ; done",
            ]
