---
- name: learning handler concept
  hosts: all
  become: yes

  tasks:
    - name: Install apache httpd  (state=present is optional)
      apt:
        name: apache2
        state: present

    - name: display apche configs
      shell:
        cmd: ls -la
    # once above task success them only we have call "restart apache again"
    # with help of notify
    - name: now install and config done
      shell: ls -la
      notify:
        - restart servers

  handlers:
    - name: restart servers
      service:
        name: apache2
        state: restarted
