---
- name: create at new file and copy host file from ansible it.
  hosts: all
  tasks:
    - name: create username file in tmp directory
      file:
        path: "/tmp/surekha.txt"
        state: touch
    - name: copy ansible hosts file on every node
      copy:
        src: "/etc/ansible/hosts"
        dest: "/tmp"

# which apache2
- name: install httpd packages and update sample webpage and start service
  hosts: all
  become: yes # root user going to excute

  tasks:
    - name: Update all packages to their latest version
      apt:
        name: "*"
        state: latest

    - name: Install apache2 httpd  (state=present is optional)
      apt:
        name: apache2
        state: present

    - name: Copy index test page
      copy:
        src: "index.html"
        dest: "/var/www/index.html"
        force: yes

    - name: Restart Apache
      service:
        name: apache2
        state: restarted
