---
- name: learn loop inside playbook
  hosts: all
  become: yes
  tasks:
    - name: Add several users on nodes
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - testuser1
        - testuser2
        - surekha
        - foo

#ansible-playbook loop.yml -K